# Generated by Django 3.1 on 2024-04-23 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_productgalary'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productgalary',
            options={'verbose_name': 'Product Gallary', 'verbose_name_plural': 'Products Gallary'},
        ),
    ]
