# Generated by Django 3.1 on 2024-04-13 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20240413_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='currency_code',
            field=models.CharField(default='USD', max_length=5),
        ),
    ]
