# Generated by Django 3.1 on 2024-04-14 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_payment_currency_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='color',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='size',
        ),
    ]
